Prisma2
astronomer/db-bootstrapper pull request #16
Opened 2020-07-02 16:34 UTC by andriisoldatenko

2020-07-06 14:22 UTC, sjmiller609 commented on main.py
> +        )}
What happens if this is run multiple times? I'm not sure, but it kind of looks to me like this fetches the DB string, then mutates it, I worry a second run would append the schema part redundantly. Can we add some unit testing around this condition, please?

2020-09-04 14:34 UTC, adam2k commented on main.py
>      click.echo("Database does not exist, creating...")
```suggestion
   click.echo("Attempting to create database...")
```

2020-09-04 16:26 UTC, andriisoldatenko commented on main.py
> +        )}
```
# In [32]: quote(quote('houston$default'), safe='%')
# Out[32]: 'houston%24default'
```

we don't have test framework or CI/CD for tests in this repo.

2020-09-04 16:55 UTC, sjmiller609 requested changes
I think we need tests to ensure that the idempotency is working. I can help get that set up

2020-09-04 22:34 UTC, sjmiller609 approved these changes
I added a test for the item of concern. If tests pass, I am good with this change.

2020-09-04 22:34 UTC, sjmiller609 commented on test/component/test_db_bootstrapper.py
> +def test_db_bootstrapper_idempotent(db_bootstrapper, kube_client):
this is the behavior I was mostly worried about

2020-09-10 16:54 UTC, kushalmalani commented on main.py
> +    logging.debug(f"Using connection string: {conn}")
Is there a typo in the debug message? f"Using

2020-09-10 16:56 UTC, kushalmalani commented on main.py
> -    except Exception as e:
Why are we removing this? Does it not ever go in except block?

2020-09-10 16:57 UTC, sjmiller609 approved these changes

2020-09-10 16:59 UTC, adam2k reviewed
This looks good to me.  I just have the single question about using the Ubuntu image instead of Alpine.

2020-09-10 16:59 UTC, adam2k commented on .circleci/config.yml
> +      resource_class: xlarge
Do we need this particular image or is there more lightweight version of linux, like alpine, that we can use that is closer to what our staging and prod envs are using?

2020-09-10 16:59 UTC, adam2k commented on test/component/test_db_bootstrapper.py
> +def test_db_bootstrapper_idempotent(db_bootstrapper, kube_client):
@sjmiller609 does this test cover everything that you were worried about?

2020-09-10 16:59 UTC, andriisoldatenko commented on main.py
> +    logging.debug(f"Using connection string: {conn}")
nope it's python f-strings https://www.python.org/dev/peps/pep-0498/

2020-09-10 17:00 UTC, andriisoldatenko commented on .circleci/config.yml
> +      resource_class: xlarge
@sjmiller609 using it for all e2e tests AFAIK.

2020-09-10 17:01 UTC, andriisoldatenko commented on main.py
> -    except Exception as e:
@sjmiller609 suggested to see error instead if hiding it from logs.

2020-09-10 17:02 UTC, andriisoldatenko commented on test/component/test_db_bootstrapper.py
> +def test_db_bootstrapper_idempotent(db_bootstrapper, kube_client):
yep.

2020-09-10 17:19 UTC, kushalmalani approved these changes

2020-09-11 13:59 UTC, ashb reviewed
LGTM from a very quick look.

2020-09-11 14:13 UTC, merged